apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p548nyxtd-python
  janus-idp.io/tekton: p548nyxtd-python
  backstage.io/kubernetes-id: p548nyxtd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p548nyxtd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
